import { useState, useEffect, useMemo } from 'react';
import { useAuth } from '../../context/AuthContext';
import { notificationService } from '../../services/notificationService';
import { DashboardCard } from '../../components/cards/DashboardCard';
import { Timeline } from '../../components/common/Timeline';
import { EmptyState } from '../../components/common/EmptyState';
import { CardSkeleton, Skeleton } from '../../components/common/LoadingSkeleton';
import { Icon } from '../../components/common/Icon';

import { collection, onSnapshot, query, where } from 'firebase/firestore';
import { db } from '../../config/firebase';

/* =========================================================================
   DATE HELPERS (FIXED PARSER)
   ========================================================================= */

function parseDateSafe(value) {
  if (!value) return null;
  if (typeof value.toDate === 'function') {
    const d = value.toDate();
    return isNaN(d) ? null : d;
  }
  if (value instanceof Date) return isNaN(value) ? null : value;
  if (typeof value === 'number') {
    const d = new Date(value);
    return isNaN(d) ? null : d;
  }
  if (typeof value !== 'string') return null;

  const str = value.trim();

  // THE FIX: Safely parse the exact DD/MM/YYYY format generated by OCR
  const parts = str.split('/');
  if (parts.length === 3) {
    const day = parseInt(parts[0], 10);
    const month = parseInt(parts[1], 10);
    const year = parseInt(parts[2], 10);
    
    if (!isNaN(day) && !isNaN(month) && !isNaN(year)) {
      const d = new Date(year, month - 1, day);
      if (d.getFullYear() === year && d.getMonth() === month - 1 && d.getDate() === day) {
        return d;
      }
    }
  }

  // Final fallback for standard strings
  const fallback = new Date(str);
  return isNaN(fallback) ? null : fallback;
}

function daysUntilSafe(value) {
  const d = parseDateSafe(value);
  if (!d) return null;
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const target = new Date(d);
  target.setHours(0, 0, 0, 0);
  return Math.round((target - today) / (1000 * 60 * 60 * 24));
}

function formatDateSafe(value) {
  const d = parseDateSafe(value);
  return d ? d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) : undefined;
}

/* =========================================================================
   STATUS / DOCUMENT-EXPIRY RESOLUTION
   ========================================================================= */

const normStatus = (s) => (s || '').toString().trim().toLowerCase().replace(/[\s-]+/g, '_');
const normPlate = (p) => (p || '').toString().toUpperCase().replace(/[^A-Z0-9]/g, '');

const VEHICLE_VISIBLE_STATUSES = ['approved', 'completed', 'paid', 'active', 'revoked'];
const APPROVED_APPLICATION_STATUSES = ['approved', 'for_payment', 'completed', 'paid', 'active'];

function resolveExpiries(vehicle, applications) {
  const plate = normPlate(vehicle.plateNumber || vehicle.vehicleDetails?.plateNumber);
  const approvedApp = applications.find(
    (a) =>
      APPROVED_APPLICATION_STATUSES.includes(normStatus(a.status)) &&
      ((vehicle.applicationId && a.id === vehicle.applicationId) ||
        (plate && normPlate(a.vehicleDetails?.plateNumber) === plate))
  );
  const pick = (key) =>
    vehicle.nlpExtractedData?.[key] || vehicle[key] || approvedApp?.nlpExtractedData?.[key] || null;

  return { orExpiry: pick('orExpiry'), licenseExpiry: pick('licenseExpiry') };
}

function stickerExpiryOf(vehicle) {
  const base = vehicle.dateIssued || vehicle.reviewedDate || vehicle.registrationDate;
  const d = parseDateSafe(base);
  if (!d) return null;
  const expiry = new Date(d);
  expiry.setFullYear(expiry.getFullYear() + 1);
  return expiry.toISOString();
}

/* =========================================================================
   LATEST APPLICATION ACTIVITY (TIMELINE)
   ========================================================================= */

function generateTimeline(app, matchedVehicle) {
  const submissionDate = formatDateSafe(app.submittedDate || app.createdAt) || 'Submitted';
  const approvalDate = formatDateSafe(matchedVehicle?.reviewedDate || app.reviewedDate || app.approvedDate) || submissionDate;
  const issuedDate = formatDateSafe(matchedVehicle?.dateIssued || app.dateIssued) || approvalDate;

  const isVehicleActive = matchedVehicle && ['active', 'approved', 'completed', 'paid'].includes(normStatus(matchedVehicle.status));
  const isVehicleRevoked = matchedVehicle && normStatus(matchedVehicle.status) === 'revoked';
  const status = isVehicleActive ? 'active' : isVehicleRevoked ? 'revoked' : normStatus(app.status);

  if (status === 'active' || status === 'completed' || status === 'paid') {
    return [
      { label: 'Application Submitted', date: submissionDate, done: true },
      { label: 'Under Review', date: submissionDate, done: true },
      { label: 'Approved', date: approvalDate, done: true },
      { label: 'Sticker Issued', date: issuedDate, done: true }
    ];
  } 
  
  if (status === 'approved' || status === 'for_payment') {
    return [
      { label: 'Application Submitted', date: submissionDate, done: true },
      { label: 'Under Review', date: submissionDate, done: true },
      { label: 'Approved', date: approvalDate, done: true },
      { label: 'Payment & Issuance', done: false }
    ];
  } 
  
  if (status === 'rejected' || status === 'revoked') {
    return [
      { label: 'Application Submitted', date: submissionDate, done: true },
      { label: 'Under Review', date: submissionDate, done: true },
      { label: status === 'revoked' ? 'Revoked' : 'Rejected', date: formatDateSafe(app.revokedDate || app.reviewedDate), done: true }
    ];
  } 
  
  return [
    { label: 'Application Submitted', date: submissionDate, done: true },
    { label: 'Under Review', done: false },
    { label: 'Approval', done: false },
    { label: 'Sticker Issued', done: false }
  ];
}

/* =========================================================================
   FIRESTORE SUBSCRIPTIONS
   ========================================================================= */

function subscribeOwned(colName, fields, ids, onData, onError) {
  const buckets = {};
  const emit = () => {
    if (Object.keys(buckets).length < fields.length) return;
    const merged = new Map();
    Object.values(buckets).forEach((list) => list.forEach((item) => merged.set(item.id, item)));
    onData(Array.from(merged.values()));
  };
  const unsubs = fields.map((field) =>
    onSnapshot(
      query(collection(db, colName), where(field, 'in', ids)),
      (snap) => {
        buckets[field] = snap.docs.map((d) => ({ id: d.id, ...d.data() }));
        emit();
      },
      (err) => {
        console.error(`[StudentDashboard] ${colName}.${field} listener failed:`, err);
        onError(err);
      }
    )
  );
  return () => unsubs.forEach((u) => u());
}

const submittedTime = (a) => parseDateSafe(a.submittedDate || a.createdAt)?.getTime() || 0;

/* =========================================================================
   PAGE
   ========================================================================= */

export default function StudentDashboard() {
  const { user } = useAuth();
  const [applications, setApplications] = useState([]);
  const [vehicles, setVehicles] = useState([]);
  const [appsLoading, setAppsLoading] = useState(true);
  const [vehiclesLoading, setVehiclesLoading] = useState(true);
  const [appsError, setAppsError] = useState(null);
  const [vehiclesError, setVehiclesError] = useState(null);

  const uid = user?.id || user?.uid;
  const userIdsKey = [user?.id, user?.uid].filter(Boolean).join('|');

  useEffect(() => {
    if (!userIdsKey) return;
    const ids = Array.from(new Set(userIdsKey.split('|')));

    const unsubApps = subscribeOwned(
      'applications',
      ['userId'],
      ids,
      (apps) => {
        apps.sort((a, b) => submittedTime(b) - submittedTime(a));
        setApplications(apps);
        setAppsError(null);
        setAppsLoading(false);
      },
      (err) => {
        setAppsError(err);
        setAppsLoading(false);
      }
    );

    const unsubVehicles = subscribeOwned(
      'vehicles',
      ['ownerId', 'userId'],
      ids,
      (vArr) => {
        vArr.sort((a, b) => (parseDateSafe(b.dateIssued)?.getTime() || 0) - (parseDateSafe(a.dateIssued)?.getTime() || 0));
        setVehicles(vArr);
        setVehiclesError(null);
        setVehiclesLoading(false);
      },
      (err) => {
        setVehiclesError(err);
        setVehiclesLoading(false);
      }
    );

    return () => {
      unsubApps();
      unsubVehicles();
    };
  }, [userIdsKey]);

  const approvedVehicles = useMemo(
    () => vehicles.filter((v) => VEHICLE_VISIBLE_STATUSES.includes(normStatus(v.status))),
    [vehicles]
  );

  const latestApplication = applications.length > 0 ? applications[0] : null;
  const activeVehicle = approvedVehicles.length > 0 ? approvedVehicles[0] : null;

  useEffect(() => {
    if (!uid) return;
    approvedVehicles.forEach((vehicle) => {
      if (normStatus(vehicle.status) === 'revoked') return;
      const { orExpiry, licenseExpiry } = resolveExpiries(vehicle, applications);

      const checks = [
        { type: 'sticker', name: 'Campus Sticker', date: stickerExpiryOf(vehicle) },
        { type: 'or', name: 'Official Receipt', date: orExpiry },
        { type: 'license', name: "Driver's License", date: licenseExpiry },
      ];

      checks.forEach((check) => {
        const days = daysUntilSafe(check.date);
        if (days === null || days > 30 || days < 0) return;

        const flagKey = `notified_${check.type}_${vehicle.id}_${check.date}`;
        if (localStorage.getItem(flagKey)) return;
        localStorage.setItem(flagKey, 'true');

        notificationService
          .createNotification({
            userId: uid,
            title: `${check.name} Expiring Soon`,
            message: `Your ${check.name} for ${vehicle.plateNumber} expires in ${days} days. Please update it in the system.`,
            type: 'warning',
          })
          .catch((err) => {
            localStorage.removeItem(flagKey);
            console.error(err);
          });
      });
    });
  }, [approvedVehicles, applications, uid]);

  return (
    <div className="flex flex-col gap-8 min-h-screen font-sans text-slate-800">
      <div className="flex flex-col gap-1">
        <h1 className="text-3xl font-extrabold tracking-tight text-slate-900">
          Welcome, {(user?.fullName || user?.name || 'User').split(' ')[0]}
        </h1>
        <p className="text-base text-slate-500 font-medium">Here's the live status of your vehicle accreditation.</p>
      </div>

      {vehiclesLoading ? (
        <div className="grid grid-cols-1 gap-6 sm:grid-cols-3">
          <CardSkeleton /><CardSkeleton /><CardSkeleton />
        </div>
      ) : vehiclesError ? (
        <div className="rounded-2xl bg-rose-50 border border-rose-200 p-6 text-sm text-rose-700">
          Could not load your vehicles: {vehiclesError.message}
        </div>
      ) : approvedVehicles.length === 0 ? (
        <div className="rounded-2xl bg-white border border-slate-200 shadow-sm p-10 text-center text-slate-500 font-medium">
          No active or approved vehicles found.
        </div>
      ) : (
        <div className="flex flex-col gap-10">
          {approvedVehicles.map((vehicle) => {
            const isRevoked = normStatus(vehicle.status) === 'revoked';
            const { orExpiry, licenseExpiry } = resolveExpiries(vehicle, applications);

            return (
              <div key={vehicle.id} className="flex flex-col gap-4">
                <div className="inline-flex items-center self-start gap-2 px-4 py-2 bg-white rounded-full border border-slate-200 shadow-sm">
                  <Icon name="car" className="w-4 h-4 text-slate-400" />
                  <h3 className="text-sm font-bold text-slate-700 uppercase tracking-widest">
                    {vehicle.plateNumber} <span className="text-slate-300 mx-1">&bull;</span> {vehicle.vehicleDetails?.vehicleType || vehicle.make || 'Vehicle'}
                  </h3>
                </div>

                <div className="grid grid-cols-1 gap-6 md:grid-cols-3">
                  <div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-6 flex flex-col items-center justify-center text-center hover:shadow-md transition-shadow">
                    <div className={`w-12 h-12 rounded-full flex items-center justify-center mb-4 ${isRevoked ? 'bg-rose-50 text-rose-500' : 'bg-emerald-50 text-emerald-500'}`}>
                      <Icon name="car" className="w-6 h-6" />
                    </div>
                    <span className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-3">
                      Vehicle Status
                    </span>
                    <div>
                      {isRevoked ? (
                        <span className="inline-flex items-center px-4 py-2 rounded-full text-sm font-bold bg-rose-100 text-rose-700 gap-1.5">
                          Revoked
                        </span>
                      ) : (
                        <span className="inline-flex items-center px-4 py-2 rounded-full text-sm font-bold bg-emerald-100 text-emerald-700 gap-1.5 shadow-sm border border-emerald-200">
                          <Icon name="check-circle" className="w-4 h-4" /> ACTIVE
                        </span>
                      )}
                    </div>
                  </div>

                  <div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-6 flex flex-col items-center justify-center text-center hover:shadow-md transition-shadow">
                    <div className="w-12 h-12 rounded-full bg-blue-50 text-blue-500 flex items-center justify-center mb-4">
                      <Icon name="sticker" className="w-6 h-6" />
                    </div>
                    <span className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">
                      Sticker Status
                    </span>
                    <h2 className="text-3xl font-extrabold font-sans text-slate-900 tracking-tight">
                      {vehicle.stickerSerial || '—'}
                    </h2>
                    <p className="text-xs font-medium text-slate-500 mt-2 flex items-center gap-1.5">
                      {vehicle.stickerSerial ? (
                        <><Icon name="check" className="w-4 h-4 text-emerald-500" /> Serial assigned</>
                      ) : 'Not yet assigned'}
                    </p>
                  </div>

                  <div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-6 relative overflow-hidden flex flex-col justify-center hover:shadow-md transition-shadow">
                    {isRevoked && <div className="absolute inset-0 bg-white/60 backdrop-blur-sm z-10 flex items-center justify-center font-bold text-rose-700 uppercase tracking-widest">Revoked</div>}

                    <div className="flex items-center gap-2 mb-5 border-b border-slate-100 pb-3">
                      <Icon name="alert-triangle" className="h-4 w-4 text-amber-500" />
                      <h3 className="text-xs font-bold text-slate-800 uppercase tracking-wider">Document Expirations</h3>
                    </div>

                    <div className="flex flex-col gap-2">
                      <ExpiryRow label="Sticker" date={stickerExpiryOf(vehicle)} />
                      <ExpiryRow label="OR Expiry" date={orExpiry} />
                      <ExpiryRow label="License" date={licenseExpiry} />
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}

      <div className="w-full mt-6 bg-white rounded-2xl border border-slate-200 shadow-sm p-6">
        <h3 className="text-lg font-bold text-slate-900 mb-6">Latest Application Activity</h3>
        {appsLoading ? (
          <div className="flex flex-col gap-4">
            <Skeleton className="h-4 w-1/3 rounded-md" />
            <Skeleton className="h-4 w-1/2 rounded-md" />
          </div>
        ) : appsError ? (
          <div className="rounded-xl bg-rose-50 border border-rose-200 p-4 text-sm text-rose-700">
            Could not load your application activity: {appsError.message}
          </div>
        ) : (latestApplication || activeVehicle) ? (
          <Timeline steps={generateTimeline(latestApplication || {}, activeVehicle)} />
        ) : (
          <EmptyState title="No applications yet" description="Register your vehicle to start the accreditation process." />
        )}
      </div>
    </div>
  );
}

function ExpiryRow({ label, date }) {
  const days = daysUntilSafe(date);
  const shown = formatDateSafe(date);

  let badgeClass = 'bg-slate-100 text-slate-600';
  let badgeText = 'Not on file';

  if (days !== null) {
    if (days < 0) {
      badgeClass = 'bg-rose-100 text-rose-700';
      badgeText = 'Expired';
    } else if (days <= 30) {
      badgeClass = 'bg-amber-100 text-amber-700';
      badgeText = `${days} days left`;
    } else {
      badgeClass = 'bg-emerald-100 text-emerald-700';
      badgeText = `${days} days left`;
    }
  }

  return (
    <div className="flex justify-between items-center py-2.5 border-b border-slate-50 last:border-0">
      <div className="flex flex-col">
        <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500">{label}</span>
        {shown && <span className="text-[11px] text-slate-400">{shown}</span>}
      </div>
      <span className={`px-2.5 py-1 rounded-full text-[11px] font-bold ${badgeClass}`}>{badgeText}</span>
    </div>
  );
}